name: Restore Node.js env
description: Node.js によるタスクランナー基盤を復元する

runs:
  using: composite
  steps:
    - name: Setup node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: ./.node-version

    - name: Restore node_modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      shell: bash
      run: npm install
